name: 📖 Documentation

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  release:
    name: 📦☁️ Release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: ⚡ Install dependencies
        run: yarn install --frozen-lockfile

      - name: 🔨 Build documentation
        run: yarn build:docs

      - name: ☁️ Publish documentation
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: docs
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
