# https://gist.github.com/paullessing/d706c8af51faca68c6ba0f9f9bae4e4b#file-release-when-tagged-yml

name: 📦☁️ Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: 📦☁️ Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          scope: '@netresearch'

      - name: ⚡ Install dependencies
        run: yarn install --frozen-lockfile

      - name: ☁️ Publish to NPM
        run: yarn publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@netresearch'

      - name: ☁️ Publish to GitHub Package Registry
        run: yarn publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Package
        run: yarn pack --filename=package.tgz

      - name: ➕ Create release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          artifacts: package.tgz
          makeLatest: true
